import streamlit as st
import os
from PIL import Image
import random 
import numpy as np

@st.cache(ttl=3600, max_entries=10)
def image_out(image):
    return Image.open(image)

def stream_run():
    st.title("FloodNet Semantic Segmentation")
    st.text("")
    st.text("") 
    st.sidebar.markdown('''
        # Labels
        ''')
    st.sidebar.image(image_out("demo_data/LBL.png"))
    st.sidebar.markdown('''
    # What is this project?
    - [FloodNet](https://arxiv.org/abs/2012.02951) is a high-resolution image dataset acquired by DJI Mavic Pro quadcopters, after Hurricane Harvey.
    - This dataset was finalized in Dec 2020 and through [FloodNet 2021](http://www.classic.grss-ieee.org/earthvision2021/challenge.html) competition we were the first ones in the world to get to work with this.
    - The image on the right displays the Semantic Segmentation maps generated by the best models of various DL architectures trained by our approach.
    - Read more about it in our [paper](https://arxiv.org/abs/2105.08655)
    ''')
    
    st.sidebar.markdown('''Liked it? Give a :star:  on GitHub [here](https://github.com/sahilkhose/FloodNet)''')

    image = "demo_data/15_4.png"
    if st.button("Generate"):  
        image_no = random.randint(0, len(os.listdir('demo_data/plt_inference')))
        image = f"demo_data/plt_inference/{image_no}.png"
    st.image(np.array(image_out(image))[:-30, 100:-80, :], use_column_width=True)  

if __name__ == "__main__":
    st.set_page_config(
    initial_sidebar_state="expanded",
    page_title="Semantic Segmentation"
    )
    stream_run()